### ISSUE TITLE
VSCode palatte doesn't show commands

### ISSUE THREAD

**Issue by vrdse** [SeeminglyScience/EditorServicesCommandSuite#19]
I can't find any of the commands in the VSCode palette.

Commands executed

    PowerShellGet\Install-Module EditorServicesCommandSuite -Scope CurrentUser
    Import-Module EditorServicesCommandSuite
    Import-EditorCommand -Module EditorServicesCommandSuite

System information

   Get-Host

    Name             : Visual Studio Code Host
    Version          : 1.4.1
    InstanceId       : ***
    UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
    CurrentCulture   : de-DE
    CurrentUICulture : de-DE
    PrivateData      :
    DebuggerEnabled  : True
    IsRunspacePushed : False
    Runspace         : System.Management.Automation.Runspaces.LocalRunspace

    Get-Command -Module EditorServicesCommandSuite

    CommandType     Name                                               Version    Source
    -----------     ----                                               -------    ------
    Function        Add-CommandToManifest                              0.3.0      EditorServicesCommandSuite
    Function        Add-ModuleQualification                            0.3.0      EditorServicesCommandSuite
    Function        Add-PinvokeMethod                                  0.3.0      EditorServicesCommandSuite
    Function        ConvertTo-LocalizationString                       0.3.0      EditorServicesCommandSuite
    Function        ConvertTo-MarkdownHelp                             0.3.0      EditorServicesCommandSuite
    Function        ConvertTo-SplatExpression                          0.3.0      EditorServicesCommandSuite
    Function        Expand-Expression                                  0.3.0      EditorServicesCommandSuite
    Function        Expand-MemberExpression                            0.3.0      EditorServicesCommandSuite
    Function        Expand-TypeImplementation                          0.3.0      EditorServicesCommandSuite
    Function        New-ESCSSettingsFile                               0.3.0      EditorServicesCommandSuite
    Function        Remove-Semicolon                                   0.3.0      EditorServicesCommandSuite
    Function        Set-HangingIndent                                  0.3.0      EditorServicesCommandSuite
    Function        Set-RuleSuppression                                0.3.0      EditorServicesCommandSuite
    Function        Set-UsingStatementOrder                            0.3.0      EditorServicesCommandSuite

The functions work just fine. However, none of the commands show up in the VSCode palette. Any ideas?

**Comment by SeeminglyScience** [comment]
Yeah, currently editor commands are registered to the sub menu "Show additional commands from PowerShell modules". 

![](http://powershell.github.io/PowerShellEditorServices/images/vsc_command_palette.png)

Right now the only way to add commands directly to the command palette is through the VSCode extension's manifest.  There's an open issue on the VSCode repo to open this up.  [Here's where you can track it](https://github.com/Microsoft/vscode/issues/1422).

In the mean time I would recommend adding a key binding for the additional commands menu, here's mine as an example:

```json
{ "key": "ctrl+shift+c",   "command": "PowerShell.ShowAdditionalCommands",
                              "when": "editorLangId == 'powershell'" },
```

**Comment by vrdse** [comment]
Ahh that makes sense, thanks!
