### ISSUE TITLE
ConvertTo-SplatExpression does seem to work under Windows 10 1903 and powershell core 6.2

### ISSUE THREAD

**Issue by ghost** [SeeminglyScience/EditorServicesCommandSuite#41]
Cannot get the editor services to load either from profile or manually 

manually no errors but when using command pallette convertto-splatexpression is not avaiable?

it maybe a config issue with windows 1903?

**Comment by SeeminglyScience** [comment]
> but when using command pallette convertto-splatexpression is not avaiable

Yeah, currently editor commands are registered to the sub menu "Show additional commands from PowerShell modules". 

![](http://powershell.github.io/PowerShellEditorServices/images/vsc_command_palette.png)

Right now the only way to add commands directly to the command palette is through the VSCode extension's manifest.  There's an open issue on the VSCode repo to open this up.  [Here's where you can track it](https://github.com/Microsoft/vscode/issues/1422).

**Comment by SeeminglyScience** [comment]
Resolved per reply https://github.com/Microsoft/vscode/issues/1422#issuecomment-496599654, closing.
