### ISSUE TITLE
PowerShell Preview extension: "No extension commands have been loaded into current session"

### ISSUE THREAD

**Issue by codaamok** [SeeminglyScience/EditorServicesCommandSuite#45]
While the PowerShell Preview VSCode extension is loaded, I opened the command palette to choose "Show additional commands from PowerShell module...". A small pop up in the bottom corner read "No extension commands have been loaded into current session".

A kind person in WinAdmins Discord pointed me to the below issue where you linked to module version 0.5.0. Just come here to say the issue I just described is no present in 0.5.0 while using PowerShell Preview extension.

https://github.com/SeeminglyScience/EditorServicesCommandSuite/issues/42#issuecomment-555014744

**Comment by SeeminglyScience** [comment]
Fixed with v1.0.0-beta1

```powershell
Install-Module EditorServicesCommandSuite -Scope CurrentUser -AllowPrerelease -Force
```
