### ISSUE TITLE
Use EditorServicesCommandSuite in PowerShell 7

### ISSUE THREAD

**Issue by constantinhager** [SeeminglyScience/EditorServicesCommandSuite#63]
I try to use the EditorServicesCommandSuite with Powershell 7.0.3 in VS Code Insiders version 1.52.0-insider.

I used user profile script in the readme:
```powershell
psedit $profile;$psEditor|% g*t|% c*e|% i* "Import-CommandSuite`n" 1 1 1 1
```

But the commands are not importing. If I run Import-CommandSuite from the integrated terminal I get 

```powershell
Import-CommandSuite: The term 'Import-CommandSuite' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

Is EditorServicesCommandSuite not supported in PowerShell 7. If not are there any plans to do that?

**Comment by SeeminglyScience** [comment]
@constantinhager Should work, what version of EditorServicesCommandSuite are you on? If you're not already on `1.0.0-beta3`, that's needed for recent versions of the PowerShell extension (and that command didn't exist prior).

**Comment by constantinhager** [comment]
Thank you for the information. Now It works with the beta version. This should absolutely be added to the readme. I was not aware of that.

**Comment by SeeminglyScience** [comment]
Very good point, I went ahead and added that to the install module line in the READDME.  Thanks for catching that!
